### ISSUE TITLE
Configuration empty after update

### ISSUE THREAD

**Issue by fuslwusl** [dc297/mqttclpro#42]
All settings got lost after update - broker settings etc.

**Comment by deepessh** [comment]
Hey

As mentioned earlier, a lot of changes have been made in the core working of the app. I have basically re-written the app in order to enable multiple brokers support and other features like offline message buffer. Please bear with me during this transition. I understand it is going to be a lot of pain.

Sincerely hope you like the new features.

Regards
Deepesh

**Comment by fuslwusl** [comment]
Ok, i just wanted to inform about this. It's not a big deal to enter the few fields again.
But when I tried to save the configuration with field "Client ID" empty there was no validation message for it but the field was required to get the config saved.

**Comment by fuslwusl** [comment]
Thanx for the great new features and for creating this great open source project!!!

**Comment by deepessh** [comment]
Great! Always happy to help the community :)

**Comment by deepessh** [comment]
By the way. I did add the validation on client ID. Let me see what's going wrong.
